#!/usr/bin/env ruby

require 'readline'
require_relative "prettyprint"
require_relative "shellprocess"


pp = PrettyPrint.new

#initialize shell
#TODO
#this needs to be passed as an arg, for now hardcoded
remote_shell = ShellProcess.new("nc -l 4445", pp)
#remote_shell = ShellProcess.new("bash", pp)

#tab complete
Readline.completion_proc = proc do |s|
  directory_list = Dir.glob("#{s}*")
  if directory_list.size > 0
    directory_list
  else
    Readline::HISTORY.grep(/^#{Regexp.escape(s)}/)
  end
end

while input = Readline.readline("$ ", true)
  break                       if input == "exit"
  puts Readline::HISTORY.to_a if input == "hist"
  # Remove blank lines from history
  Readline::HISTORY.pop if input == ""
  remote_shell.input(input)
end